### ISSUE TITLE
Cannot use the tool on cookies

### ISSUE THREAD

**Issue by YonkoSultan** [hansmach1ne/LFImap#121]
Reproduce :

```bash
┌──(darkaxe㉿Sultan)-[~]
└─$ lfimap -U "http://wcamxwl32pue3e6mw93xjqgt7zr8873o7oy7tw3y-web.cybertalentslabs.com/policy.php" -H "Cookie: readme= Yonko" --placeholder=Yonko -a
[-] No arguments to test. Exiting...
```

I've already figured out the problem and it seems that it occurs in multiple places in the project files,
 
For example `lfimap.py` :
```python3
    found_in_headvalues = args['param'] in (
            str(value) for value in args['httpheaders'].values())
            
```
This will loop inside the cookie name and value instead of value only so :
```python3
args['param'] in ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Safari/537.3', '*/*', 'Close', 'readme=Yonko')
```
which will be `false`, although it is not.

So you either take the cookie value only without the name or you just create another loop on the header values, something like this :

```python3
        for i in ([str(value) for value in args['httpheaders'].values()]):
             if args['param'] in i:
                 found_in_headvalues = True
```

I've also tried this on the -C argument for cookies, but I got the same result.

**Comment by hansmach1ne** [comment]
@YonkoSultan Thank You for raising this issue, reproduced it and hopefully fixed in the latest commit.
Can you git pull and re-try it.

The issue was within the Python `in` keyword as it checks for exact matches when utilized in the dictionary values context. We needed a substring match and I tried elegantly solving this via `any` construct. Hopefully this fixed the issue.
